[build]
  dockerfilePath = "Dockerfile"
  buildArgs = { GITHUB_TOKEN = "${{ GITHUB_TOKEN }}" }

[deploy]
  startCommand = "./scripts/docker-entrypoint.sh ./auth7 start"
  healthcheckPath = "/health/live"
  healthcheckTimeout = 300
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 3
